config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  
  layout "enter_layout"
  
 before_action :get_user,         only: [:edit, :update]
  before_action :valid_user,       only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_url
    else
      flash.now[:danger] = "Email address not found"
      render 'new'
    end
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @user.update_attributes(user_params)
      log_in @user
      flash[:success] = "Password has been reset."
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    # Before filters

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # Confirms a valid user.
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end

    # Checks expiration of reset token.
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired."
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, "Signup") %>
 <%= form_for(@user, url: password_reset_path(params[:id]), :html => { :class => "no-margin"}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
      <fieldset>
          <%= hidden_field_tag :email, @user.email %>
					<div class="form-group">
                       <%= f.label :password %>

                        <div class="input-group input-group-lg">
                                <span class="input-group-addon">
                                    <i class="icon-lock"></i>
                                </span>
                            <%= f.password_field :password, placeholder:"Your password", class:"form-control input-lg" %>
                        </div>

                    </div>
					<div class="form-group">
                       <%= f.label :password_confirmation, "Confirmation" %>

                        <div class="input-group input-group-lg">
                                <span class="input-group-addon">
                                    <i class="icon-lock"></i>
                                </span>
                            <%= f.password_field :password_confirmation, placeholder:"Confirm your password", class:"form-control input-lg" %>
                        </div>

                    </div>
                </fieldset>
                <div class="form-actions">
                <label class="checkbox"></label>
                <%= f.submit "Update password", class: "btn btn-warning pull-right" %>
                </div>
    <% end %>
  

app/views/password_resets/new.html.erb
<% provide(:title, "Log in") %>
 <%= form_for(:password_reset, url: password_resets_path, :html => { :class => "no-margin"}) do |f| %>
      <fieldset>

                    <div class="form-group">
                       <%= f.label :email %>

                        <div class="input-group input-group-lg">
                                <span class="input-group-addon">
                                    <i class="icon-envelope"></i>
                                </span>
                            <%= f.email_field :email, placeholder:"Your Email", class:"form-control input-lg" %>
                        </div>

                    </div>

                </fieldset>
                <div class="form-actions">
                <label class="checkbox"></label>
                <%= f.submit "Submit", class: "btn btn-warning pull-right" %>
                </div>
    <% end %>
  