config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer>
        <div class="bottom-nav footer">
            <nav>
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "About",   about_path %></li>
                    <li><%= link_to "Contact", contact_path %></li>
                    <li><a href="http://news.railstutorial.org/">News</a></li>
                </ul>
            </nav>
            <p style="padding-top:5px">By Abtin Shahkarami</p>
        </div>
</footer>

app/views/layouts/_header.html.erb
<header>
        <div class="container">
            <div class="top-navbar header b-b">
                <a data-original-title="Toggle navigation" class="toggle-side-nav pull-left" href="#"><i class="icon-reorder"></i> </a>
                <div class="brand pull-left">
                    <a href="/"><img src="/assets/logo.png" width="147" height="33"></a>
                </div>
                <% if logged_in? %>
                <ul class="nav navbar-nav navbar-right  hidden-xs">
               <li class="dropdown user  hidden-xs">
                  <a data-toggle="dropdown" class="dropdown-toggle" href="#"> <i class="icon-male"></i> <span class="username">your account</span> <i class="icon-caret-down small"></i> </a>
                  <ul class="dropdown-menu">
                     <li><%= link_to current_user do %><i class="icon-user"></i> Profile<% end %></li>
                     <li><%= link_to edit_user_path(current_user) do %><i class="icon-tasks"></i> Settings<% end %></li>
                     <li class="divider"></li>
                     <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                  </ul>
               </li>
            </ul>
             <% end %>
            </div>
        </div>
</header>

app/views/layouts/_leftmenu.html.erb
<div class="left-nav">
            <div id="side-nav">
                <ul id="nav">
                    <li class="current">
                        <%= link_to root_path do %>
                     <i class="icon-home"></i>Home
                         <% end %>
                    </li>
                    <% if logged_in? %>
                    <li class="current">
					    <%= link_to users_path do %>
                     <i class="icon-group"></i>Users
                         <% end %>
                    </li>
                    <% end %>
                    <li class="current">
                        <%= link_to about_path do %>
                     <i class="icon-info-sign"></i>About
                         <% end %>
                    </li>
                    <li class="current">
                        <%= link_to contact_path do %>
                     <i class="icon-envelope"></i>Contact
                         <% end %>
                    </li>
                    <li class="current">
                        <%= link_to help_path do %>
                     <i class="icon-exclamation-sign"></i>Help
                         <% end %>
                    </li>
                    <% if !logged_in? %>
					<li class="current">
					    <%= link_to signup_path do %>
                     <i class="icon-user"></i>Sign up
                         <% end %>
                    </li>
					<li class="current">
					    <%= link_to login_path do %>
                     <i class="icon-signin"></i>Log in
                         <% end %>
                    </li>
                    <% end %>
                </ul>
            </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="wrapper">
      <%= render 'layouts/leftmenu' %>
      <div class="page-content">
      <div class="content container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      </div>
      </div>
    </div>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/enter_layout.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title)) %></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Bootstrap -->
<%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>

</head>
<body>
<div class="login-logo">
	<img src="/assets/logo.png" width="147" height="33"> 
    </div>

<div class="widget">
<div class="login-content">
  <div class="widget-content" style="padding-bottom:0;">
  <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
  <%= yield %>
  
  </div>
   </div>
</div>

</body>
</html>